// src/lib/components/Ecap.svelte
<div class="ecap-container">
	<!-- Begin Mailchimp Signup Form -->
	<link
		href="//cdn-images.mailchimp.com/embedcode/classic-10_7_dtp.css"
		rel="stylesheet"
		type="text/css"
	/>
	<h2>Sign up for our mailing list!</h2>
	<div id="mc_embed_signup">
		<form
			action="https://travelsaveandbemerry.us20.list-manage.com/subscribe/post?u=6295ef881a181db0a3aabb81b&amp;id=d8b406e59a"
			method="post"
			id="mc-embedded-subscribe-form"
			name="mc-embedded-subscribe-form"
			class="validate"
			target="_blank"
			novalidate
		>
			<div id="mc_embed_signup_scroll">
				<div class="mc-field-group">
					<label for="mce-EMAIL">Email Address <span class="asterisk">*</span> </label>
					<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" />
				</div>
				<div id="mce-responses" class="clear foot">
					<div class="response" id="mce-error-response" style="display: none" />
					<div class="response" id="mce-success-response" style="display: none" />
				</div>
				<!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
				<div style="position: absolute; left: -5000px" aria-hidden="true">
					<input
						type="text"
						name="b_6295ef881a181db0a3aabb81b_d8b406e59a"
						tabindex="-1"
						value=""
					/>
				</div>
				<div class="optionalParent">
					<div class="clear foot">
						<input
							type="submit"
							value="Subscribe"
							name="subscribe"
							id="mc-embedded-subscribe"
							class="button"
						/>
						<!-- <p class="brandingLogo">
                                <a
                                    href="http://eepurl.com/h01bFX"
                                    title="Mailchimp - email marketing made easy and fun"
                                    ><img
                                        src="https://eep.io/mc-cdn-images/template_images/branding_logo_text_dark_dtp.svg"
                                /></a>
                            </p> -->
					</div>
				</div>
			</div>
		</form>
	</div>
	<script
		type="text/javascript"
		src="//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js"
	></script>
	<script type="text/javascript">
		(function ($) {
			window.fnames = new Array();
			window.ftypes = new Array();
			fnames[0] = 'EMAIL';
			ftypes[0] = 'email';
			fnames[1] = 'FNAME';
			ftypes[1] = 'text';
			fnames[2] = 'LNAME';
			ftypes[2] = 'text';
		})(jQuery);
		var $mcj = jQuery.noConflict(true);
	</script>
</div>

<style>
	.ecap-container {
		margin: var(--large-margin) 0;
		background-color: var(--white);
		padding: 5% 20%;
		box-shadow: var(--shadowColor);
	}
	.ecap-container h2 {
		margin: 0 var(--large-margin) 0;
	}
	#mc_embed_signup form {
		padding: 0;
		margin: 0 var(--large-margin) 0;
	}
	#mce-responses {
		margin: 0;
		padding: 0;
	}
	#mc_embed_signup div.response {
		margin: 0.5rem 0;
		padding: 0;
	}
</style>

// components/Ecap.vue
<template>
    <div class="ecap-container">
        <!-- Begin Mailchimp Signup Form -->
        <link
            href="//cdn-images.mailchimp.com/embedcode/classic-10_7_dtp.css"
            rel="stylesheet"
            type="text/css"
        />
        <h2>Sign up for our mailing list!</h2>
        <div id="mc_embed_signup">
            <form
                action="https://travelsaveandbemerry.us20.list-manage.com/subscribe/post?u=6295ef881a181db0a3aabb81b&amp;id=d8b406e59a"
                method="post"
                id="mc-embedded-subscribe-form"
                name="mc-embedded-subscribe-form"
                class="validate"
                target="_blank"
                novalidate
            >
                <div id="mc_embed_signup_scroll">
                    <div class="mc-field-group">
                        <label for="mce-EMAIL"
                            >Email Address <span class="asterisk">*</span>
                        </label>
                        <input
                            type="email"
                            value=""
                            name="EMAIL"
                            class="required email"
                            id="mce-EMAIL"
                        />
                    </div>
                    <div id="mce-responses" class="clear foot">
                        <div
                            class="response"
                            id="mce-error-response"
                            style="display: none"
                        ></div>
                        <div
                            class="response"
                            id="mce-success-response"
                            style="display: none"
                        ></div>
                    </div>
                    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                    <div
                        style="position: absolute; left: -5000px"
                        aria-hidden="true"
                    >
                        <input
                            type="text"
                            name="b_6295ef881a181db0a3aabb81b_d8b406e59a"
                            tabindex="-1"
                            value=""
                        />
                    </div>
                    <div class="optionalParent">
                        <div class="clear foot">
                            <input
                                type="submit"
                                value="Subscribe"
                                name="subscribe"
                                id="mc-embedded-subscribe"
                                class="button"
                            />
                            <!-- <p class="brandingLogo">
                                <a
                                    href="http://eepurl.com/h01bFX"
                                    title="Mailchimp - email marketing made easy and fun"
                                    ><img
                                        src="https://eep.io/mc-cdn-images/template_images/branding_logo_text_dark_dtp.svg"
                                /></a>
                            </p> -->
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <script
            type="text/javascript"
            src="//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js"
        ></script>
        <script type="text/javascript">
            ;(function ($) {
                window.fnames = new Array()
                window.ftypes = new Array()
                fnames[0] = 'EMAIL'
                ftypes[0] = 'email'
                fnames[1] = 'FNAME'
                ftypes[1] = 'text'
                fnames[2] = 'LNAME'
                ftypes[2] = 'text'
            })(jQuery)
            var $mcj = jQuery.noConflict(true)
        </script>
        <!--End mc_embed_signup-->
    </div>
</template>

<style scoped>
.ecap-container {
    margin: var(--large-margin) 0;
    background-color: var(--white);
    padding: 5% 20%;
    box-shadow: var(--shadowColor);
}
.ecap-container h2 {
    margin: 0 var(--large-margin) 0;
}
#mc_embed_signup form {
    padding: 0;
    margin: 0 var(--large-margin) 0;
}
#mce-responses {
    margin: 0;
    padding: 0;
}
#mc_embed_signup div.response {
    margin: 0.5rem 0;
    padding: 0;
}
</style>
